### ISSUE TITLE
Building on OSX 10.10.5 fails

### ISSUE THREAD

**Issue by arnold-maderthaner** [Lyndir/MasterPassword#113]
Hi !

I'm trying to build the command line client for masterpassword on OSX 10.10.5 but it fails with the following error:

Fetching: scrypt, using git-svn...
Initialized empty Git repository in /Users/arnold/Downloads/masterpassword-cli/lib/scrypt/.git/
Filesystem has no item: Unable to connect to a repository at URL 'http://scrypt.googlecode.com/svn': 'http://scrypt.googlecode.com/svn' path not found at /Applications/Xcode.app/Contents/Developer/usr/share/git-core/perl/Git/SVN.pm line 311.

do you know how to fix it ?

**Comment by merten** [comment]
Apparently, the project repository for scrypt changed. To work around this, you can force the build script to fetch a tarball from the masterpasswordapp website instead of using the svn.

Open the following file and remove the line starting with `svn=`

`MasterPassword/C/lib/scrypt/.source`

Alternatively, you should be able to download the file manually and place it in the `lib/` folder. 

http://masterpasswordapp.com/libscrypt-b12b554.tar.gz

**Comment by lhunath** [comment]
@arnold-maderthaner Can you provide the complete build output?  It's supposed to use the `git` source, not the `svn` source.  Not sure why it's skipping `git` for you.

**Comment by lhunath** [comment]
Oh, sorry, this issue was fixed by cdaf8f99d5cfa60d7fca9c9ef0828924ad45b6de
