### ISSUE TITLE
Feature Request: Sync sites/sitesetting between devices

### ISSUE THREAD

**Issue by arnold-maderthaner** [Lyndir/MasterPassword#115]
It would be great to have a possibility to sync the sites created with the settings (like which password type,version is used atm) between devices as it needs to be remembered at the moment. I already have some sites that don't work with the default "long" type password and had to switch to a simpler one. If I need to login now on another device to the site I need to remember which type of password (and version) I used. So synching this settings across devices would make the solution much easier :) 👍

**Comment by djrieger** [comment]
+1

**Comment by arnold-maderthaner** [comment]
is this something you would consider to implement or how could this be easily achieved ?

**Comment by adamczykm** [comment]
@arnold-maderthaner 
There is an option to import/export .mpsites . Using this you can achieve manual synchronization. Nevertheless it's not convienient and some integrations will be super useful here, i.e. syncing by dropbox or owncloud, or sthing..

**Comment by lhunath** [comment]
You should be able to export to dropbox and open the export file in dropbox on another iOS device.  You can also import the file into the Mac app.

At some point in the past, Master Password used Core Data for iCloud to synchronize site data between iOS devices and Mac, but this proved to cause more problems than it solved and was nix'ed.  Sync proposes some very challenging problems, in particular when two offline devices add the same sites with different configurations and iCloud was causing a lot of grief for all sorts of reasons (many of them Apple-related, their iCloud integration was extremely buggy back then).

Since Master Password is essentially a stateless solution, it was then decided that sync was low priority and the export/import functionality was an adequate substitute until more time could be invested into a reliable solution.

Any sync solution should be:
- Cross-platform
- Completely transparent and inspectable / verifiable.
- Standardized.
- Rock-solid and reliable.

This is something I'm interested in looking into, but it's not a trivial feature.  It'll require time and effort which I currently rather allocate to different features of the app.

(If only I could do this thing full-time)

**Comment by adamczykm** [comment]
@lhunath 
If it was possible to manually pass the location of the sites file you could provide a path to automatically synchronized file which is some kind of sensible workaround (additionally backup copy on every write in the default location or sthing like that).

**Comment by lhunath** [comment]
https://project.lyndir.com/youtrack/issue/MP-34

**Comment by Mylainos** [comment]
With an WebExtension it's possible to [connect with native app](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Native_messaging) and the webext can use the sync of the browser. And no need to copying the password, the form is populated like with the password manager of the browser.

**Comment by pl0pix** [comment]
I want to add that syncing of _login names_ and _security questions_ is needed also to get the usability of MasterPassword to a _painless_ state.

Syncing five devices isn't fun right now.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
