### ISSUE TITLE
MP-8 Consider a more dynamic template system.

### ISSUE THREAD

**Issue by lhunath** [Lyndir/MasterPassword#130]
https://project.lyndir.com/youtrack/issue/MP-8

There are currently a limited number of templates.  People have expressed an interest in more templates.  The primary reason for keeping the number of templates low is to keep it feasible to do password recovery after you've lost site state.

If we can find a way to implement more templates without significantly hampering the ability to find the right template to use after losing state, that would be great.  Eg. template classes and then a complexity slider within that class.

**Comment by Mylainos** [comment]
I propose to change a little bit the templates. x represent the number of characters.
PIN(x)
Basic(x)
Complex(x) - Short, Medium and Long Password
Maximum(x)
[Diceware](https://en.wikipedia.org/wiki/Diceware)(x) - Words from a diceware list (I think [the list of the EFF](https://www.eff.org/deeplinks/2016/07/new-wordlists-random-passphrases) is better than the original). x represent the number of words.

And maybe advanced settings like in KeePass
![keepass1](https://cloud.githubusercontent.com/assets/6844161/21872015/3b07029e-d866-11e6-89db-2b24ab585f15.png)
![keepass2](https://cloud.githubusercontent.com/assets/6844161/21872016/3b0b5e16-d866-11e6-89f6-9f04e3454667.png)

**Comment by smichel17** [comment]
>The primary reason for keeping the number of templates low is to keep it feasible to do password recovery after you've lost site state.

A more complex templating system might also hinder the user of mpw on multiple devices.

@lhunath Are there any specific templates that users have expressed interest in? Maybe we could try to improve the existing templates instead of just adding more.

---

Here's an iteration on @Mylainos' idea: We could use two controls: one for length/type and one for complexity. Options for length/type might be:

- Pin
- Short
- Long
- Phrase

Then for complexity we could have a switch: choose between simple and complex. The options would map like this:

- Pin
  - Simple -> 4 numbers
  - Complex -> 6 or 8 numbers
- Short
  - Simple -> Current "GeneratedBasic" (8)
  - Complex -> Current "GeneratedMedium" (8)
- Long
  - Simple -> Current "GeneratedLong" (14)
  - Complex -> Current "GeneratedMaximum" (20)
- Phrase
  - Simple -> 6 word diceware passphrase
  - Complex -> 7 or 8 word diceware passphrase

---

The largest downside of this is that there's no longer a recognizable order to the different types. "Is Short/Complex more or less secure than Medium/Simple?" We could get around this by having a number or progress bar somewhere showing how secure the generated password is.

**Comment by Mylainos** [comment]
We could calculate the entropy in the worst case (the attacker know what template is used) for each option and show it.

**Comment by Mylainos** [comment]
This solution is easier but there's a loss in flexibility for example my bank only allow me to have a PIN with 12 characters max in order to access my account but there is no good choice for the number of characters, no one will agree on what's the best. Maybe this solution with an advanced tab where one can choose the length is a good compromise.

**Comment by smichel17** [comment]
You could add that, or make the 'length' setting more variable, but the more options you offer someone, the harder recovery and sync between devices becomes. If I needed to sync between devices, I'd use a password manager designed for sync.

That's why I'm curious what other password options someone would want, and maybe the existing templates can be improved. For example, I'm really not sure what the use case for `GeneratedShort` is. Who uses a 4 char alphanumeric password?

**Comment by promeneur** [comment]
i confirm there is a need for a 8 pin password
see my report here
https://github.com/ttyridal/masterpassword-firefox/issues/45

thanks

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
