### ISSUE TITLE
Observing the identicon while the master password is being typed leaks the password

### ISSUE THREAD

**Issue by vks** [Lyndir/MasterPassword#138]
By observing the identicon for each letter it is trivial to guess the password. See https://github.com/lesspass/lesspass/issues/48.

A fix would be to only show the identicon after a minimal amount of letters was entered or after the password was submitted.

**Comment by ewirch** [comment]
A benefit of the identicon is to verify the password before actually submitting it, because a typo here costs me precious seconds (wait for the key generation, close the app, reopen it).

An additional approach would be to wait a short period after the last key stroke before updating the identicon. 500ms would be enough for fast typers.

**Comment by adamczykm** [comment]
Crucial!

**Comment by TheRealMarnes** [comment]
Which identicon is being talked about here? In the official app I see only static images. Only the unofficial app by someone else (which honestly I find much better) does have this weird cryptic icon that tells me nothing but changes with each input.

**Comment by adamczykm** [comment]
The Android app for example

**Comment by TheRealMarnes** [comment]
@adamczykm yes... but which one? I have the official one and the 3rd party one from the play store. The offical one by maarten doesn't have anything but static images. All I can imagine is being talked about here are the weird icons in the unofficial app (the one with the flat theme), which nobody here can change.

**Comment by lhunath** [comment]
Currently, the identicon has only been implemented for the C and Java apps.
