### ISSUE TITLE
Compatibilitiy with MS Windows?

### ISSUE THREAD

**Issue by teknowledgist** [Lyndir/MasterPassword#170]
Based on the OS X (MacOS) focus, I'm guessing mentioning the dominant desktop platform is a bit dangerous, but I think there is a lot of potential for MasterPassword.  Thus a few questions...

1. Could a brief statement about MasterPassword and Windows be included somewhere?  At the very least, it should say it might work, but Windows isn't supported.
2. It looks like the Java GUI release is a new thing.  At the moment I don't see a v2.5 release, so I'm curious if the Java GUI will be continued.
3. I don't believe the CLI version is really "platform independent" as the documentation states.
4. Does the Java GUI have any option for arguments so it can be used "headless"?
5. If the Java GUI will be kept relatively up-to-date, is there any objection to me creating a [Chocolatey](https://chocolatey.org/) package?
6. Does anyone know of a .NET or PowerShell version/fork of this algorithm?

Thanks.

**Comment by lhunath** [comment]
This isn't really the right forum for these types of questions since they aren't really "an issue" or "feature-topical", but let me address your points in turn:

1, 2. We don't really care about macOS over Windows or anything like that, it's just that I happen to be a developer with Java & ObjC experience, and with little to no experience developing for the Windows platform/APIs.  I welcome any efforts/contributions to make MP natively available on Windows, and there have been some limited efforts in that direction.  For now, the Java GUI is the best I can do.  Since the Java GUI is platform-independent, I call it a "desktop GUI".  I understand your desire for clarification of what Windows people should do, and perhaps some guidance to that effect might be beneficial (at the very least, a hint that Windows users may need to install the Java JRE).
3. It was written with the platform-independent C standard library in mind; I haven't personally tested it on Windows, but it should be fine; at the very least the library should be.
4. There is a Java CLI.  Does this satisfy your requirement?
5. It will be, and by all means; sounds like a great idea.  I don't know what the capabilities of Chocolatey are, but ensuring the JRE is present and perhaps even making a symlink to the JAR that has a hotkey on it similar to what the macOS app provides (eg. ctrl-alt-p), would be great.
6. 
https://github.com/jimbojetset/MasterPasswordClass
https://github.com/FlyMontag/MasterPasswordUWP
https://github.com/Lyndir/MasterPassword/tree/windows/MasterPassword/CSharp

**Comment by teknowledgist** [comment]
Sorry.  I didn't see the forum previously.  

3, 4. I'm not very familiar with Java, so maybe that is the issue, but I haven't a clue how [the instructions here](https://github.com/Lyndir/MasterPassword/#native-cli) are can be made to work in Windows.  Maybe a bit more detail would help.

5.. I have submitted a [Chocolatey package for MasterPassword to the public repository](https://chocolatey.org/packages/mpw/2.4).  It will take a few days for the moderators to test and approve of it.  Assuming it will be approved, if Chocolatey is installed and working on a Windows computer, MasterPassword can be installed as simple as:
```
choco install mpw
```
I tried to prep for automated update, but I won't really know if that works until I can test it against the next release.

6.. Thanks.  If I ever find the time, I'm going to try to understand the code enough to try to make a PowerShell version.  Of course, pigs may fly before that happens.

**Comment by lhunath** [comment]
Note:
1. The masterpassword-gui JAR's version is 2.3
2. Since your package file references the version number explicitly, you should probably link to the fixed-version URL: https://ssl.masterpasswordapp.com/masterpassword-gui-2.3.jar

**Comment by teknowledgist** [comment]
Doh!  My uncertainty with the version is why I ask (indirectly) in this issue and [in the forum](http://help.masterpasswordapp.com/help/discussions/questions/249-what-version-am-i-using) about the java version.  

The automatic package updater is intended to scrape the most current version and the download url from a web page.  Is there a URL with information on the java release version from which I (or a script) can determine the version and download URL?

If 2.3 is the version, how come in the [releases](https://github.com/Lyndir/MasterPassword/releases) there is a "2.4-java" item?  

To be honest, I'm not sure how Chocolatey.org handles errors in version submission, but I'll see what I can do to fix the issue.

**Comment by lhunath** [comment]
The 2.4-java tag contains only Android changes.

I'm pretty sure your chocolatey package descriptor should be versioned, not abstract and "current".  That is not how package managers tend to work.  Also note that the descriptor references a SHA to verify against the downloaded package and as a result, must be version-specific.

**Comment by teknowledgist** [comment]
> The 2.4-java tag contains only Android changes.

Ah!  I'm still stuck trying to determine the (future) desktop/gui version (available or installed).

> I'm pretty sure your chocolatey package descriptor should be versioned

You are correct.  I'm just not super familiar with package managers and am/was not certain I could slip in an earlier version that the latest.

I have corrected the version and download URL and re-submitted.  Sorry for the confusion.

**Comment by lhunath** [comment]
No problem whatsoever, we're only learning.

**Comment by teknowledgist** [comment]
I neglected to respond here, but I thought I should point out that the [Chocolatey package for MasterPassword](https://chocolatey.org/packages/mpw) is approved (for a while now).  

I will try to update the package as MPW is updated.  Until there is a web page that will allow me to determine the current Desktop GUI version available for download, I will (unfortunately) have to update it manually as I notice.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.
