### ISSUE TITLE
I've got some suggestions.

### ISSUE THREAD

**Issue by cryptogun** [Lyndir/MasterPassword#182]
I'm using MasterPassword under ios now, by the way.
1. Why not support **custom pattern** mode? Like [my design](https://github.com/cryptogun/keepass_profile): `Nixi tiyo cote vuvi.` Easy to type, less typo, less Caps, no special characters, yet longer for the sake of entropy.   
Or builtin in the future :)
1. Better show some **pattern example** on pattern selection page.
1. How to **sync** password **counter**?
1. **Is** output file **encrypted** using master password and symmetric encryption?
1. What about **downgrade button** for password counter if I accidently increased it?
1. What if website **domain name changed**? I would recommand to type the common name of a website instead.
1. If I use common name for site name as metioned above, does it supports **UTF-8** like `中文`?   
i.e. a `UTF-8 site name` generates the same password under all platforms?
1. **Fingerprint faking** is possible as google says, so `TouchID` is not so powerful as `master password`.
1. **Fake entrance** support. i.e. wrong password can also enter an account, but passwords are incorrect. Maybe copying sitename/username, that user marked safe to public, to make the fake entrance more vivid.
1. Option to **hide account** (username) while login for the `plausible deniability` (like VeraCrypt did) and support for `travel mode` (like 1password did).
1. Better use [bcrypt or scrypt](https://crypto.stackexchange.com/questions/480/are-there-public-slow-but-strong-algorithms-out-there-that-resist-brute-force-at) to **slow down** brute force attack(like used in VeraCrypt decryption). That may require an incompatible upgrade.

I think an ideal password management would be like this:

|level|username|password|use case|description|
|------|-------------|-------------|------------|---------------|
|basic|full name|123456 / saved password / TouchID|cyber cafe / open network / working office / un-trustable PC / keylogger virus|for website / password that's not important. small loss if hacked|
|secret|nickname|**********|at home / healthy PC / money or privacy related|for important accounts. better be invisible|
|fatal|||deep web / political dissident...|use diceware + VeraCrypt hidden volume|

**Comment by lhunath** [comment]
Github issues are topical, for these types of questions, an email works better or head over to http://help.masterpasswordapp.com.  Regardless, per your questions:

1. See #130 - also, your suggestion sounds very similar to Master Password's "phrase" template.
2. This is a good suggestion, you can make a separate issue for it to track progress on it.  The macOS app already does this.
3. Master Password doesn't implement syncing at this point, though you can effectuate this through export files.
4. Master Password's export files are not encrypted.  You can make two types of export files: one that includes all your passwords in clear-text for you to see (eg. so you can print it), and a type that omits all secrets so that the export file can be used to regenerate any passwords without it being a risk if the file was leaked.  In the latter case, personal passwords are included as an aes encrypted blob.
5. Hold your finger down on the counter.
6. Website domains don't normally change since 1. they hold DNS authority and 2. it would invalidate any and all links to the company's website and services.  We recommend the domain name because it is a standardized identifier.  Things like "common names" are vague, ambiguous, and tend to invite many errors even as subtle as capitalization which will make recovering passwords for the site needlessly frustrating.
7. Yes, you can use unicode in your site names.
8. TouchID is really just a convenience feature for those who opt into it.  The security implication of it is theirs to make, individually.  The app makes it clear that this causes the master key to be stored in the device's encrypted keychain which is guarded by its secure enclave.  Apple's TouchID sensor is very well implemented in comparison to some alternatives on the market, but nevertheless incurs a security/convenience cost-benefit.
9. You can change your user's master password at any time, allowing you to log into it with a fake master password that yields all wrong passwords.  I recommend you do something like this when eg. crossing the border to certain countries.  When you are safe again, you can change the master password back to the correct one to regain access to the correct passwords.  Alternatively, you could just NOT create a user in the app and use the emergency generator instead (shake the device).
10. I believe my point in [9] adequately addresses these concerns.  But you can also just export your sites and delete your user.  Hiding things is a dubious security feature and is NOT real plausible deniability.  If authorities obtain access to your phone, it would be likely that they will discover that there is data on your phone representing a hidden account.  Real plausible deniability does not leave these traces.
11. Master Password uses scrypt to frustrate brute-force attack attempts on a user.

I don't really understand what you're saying with your table.

**Comment by cryptogun** [comment]
Thanks for your answers. I thought it'd be impolite opening tens of issues at a time :)  Help page is great, forum like. I thought there's only a faq page.
I don't know too much about cryptography. My major is EE, yet I'm paranoid about privacy.
6. You are right. Common name can have many variety and easy to forget.
9. Found it. Hold down the avatar and reset the master password. Change back and everything's back. Great!
10. I heard that in Britain if you refuse to hand out the correct password you still goto jail for 2 years. Reset the master password won't help. So I still prefer the option of auto deletion once you click `Sign out` button, so that there's no evidence that I've hided something. It'd be good to backup the counters and hand typed passwords before the deletion. Yet backup breaks plausible deniability. I have an idea:
  1. Every app creates 10 slots of dirts (true random bits).
  2. While on backup replace one slot with new dirt: `hash(username, master_passwd) + enc(counter, custom_passwd)` (need to avoid collision). They all look like dirts, and any application has 10 slots of dirts. it's the app's default and fault, I didn't do/hide any crime, I am innocent.
  3. Different platforms may generate the same/identical backup. `enc(backup)` with app specific key solves that.
  4. On re-register, check the hash header of every slot, if match, restore.
`Emergency generator` is good for "emergency". But it requires many typing and counter/pattern guessing. Not good for everyday use. Via `auto-delete and manually-restore` we can re-enter our account without guessing.

What I wanna say in that table is: I should divide my passwords into 3 categories according to their importance, so I need to create 3 accounts in an app. An account here means a username with a master password.
  - Account 1 can be access directly, protected by screen lock is enough.
  - Account 2 is able to `auto-delete and manually-restore`, protected by a strong pass phrase.
  - Account 3 is not in the app. Just for convenience use. It should be bury in VeraCrypt partition.
My imagine cases (I forgot the terminology in cryptography) are:
  - I use MasterPassword in PC. The computer I'm using might be infect by virus. I wanna login to `reddit` and read some news, if I type in my master password into the app, the virus might figure out my `amazon` password. Then `credit card`. Then `Freenet` secret key. So division is important.
Thank you for reading so many words :)

P.S. I saw there're 21 combinations of `Long Password`, e.g. `CvcvnoCvcvCvcv`. That's too much. Human likes fixed patterns. I still recommand my `cvcv`... patterns :) For `CvcvnoCvcvCvcv` x 21, I would append another `a-z` instead of so many variants.
P.S2. `I once had a red ball | 27 thousand years` is incorrect. The key is random. There're reports about people using common known sentance as pass phrase and thought that it can stand thousand years. No, it is like "passw0rd" or "123456".
Cheers,
