### ISSUE TITLE
Scrypt isn’t being applied correctly?!

### ISSUE THREAD

**Issue by peter-peter** [Lyndir/MasterPassword#200]
I did some research on password hashers and came across these critical notes on Master Password:

https://palant.de/2016/04/20/security-considerations-for-password-generators#fn8802245455717d2bceea74

https://anarc.at/blog/2017-03-02-hashers-history/#other-implementations

**Comment by lhunath** [comment]
This guy has no clue what he's talking about.  It's easy to say something like, "X isn't being done properly", and words like that do a lot of damage since in the eyes of a reader who has no knowledge to check the claim, it just sounds like a red flag.

To give you a vague idea about what it really means to perform a SHA-256 (round 2), the thing this author claims is making the solution "weak" by avoiding scrypt, perhaps consider this video:
https://www.youtube.com/watch?v=S9JGmA5_unY

The strength of the second phase is derived from the fact that it performs a SHA-256 on a 64-byte message.  Note that the video talks about a 256 bit message.  But Master Password uses a 64-byte message, which is 512 bit, so multiply the cost suggested by this video by itself once more.

**Comment by lhunath** [comment]
To add some extra context; the first phase uses scrypt because the hash's message length (ie. the user's master password) is extremely low in entropy, probably not even 32-bit.  To pass such a message through SHA-256 would make brute-forcing it fairly simple.  In terms of the above video, 32-bit is a single "4 billion".  The video even goes as far as to suggest that you could outfit your computer to be able to calculate 4 billion hashes (guesses) per second.  So clearly, this first phase uses a message far too short to be resistant against breaking the password.  This is why we use scrypt here, which slows this process down enough to make brute-forcing passwords both outlandishly expensive (in RAM cost) and time-consuming.

But for the second phase, our message is 512-bit, that's 16 of those "4 billions".  Note that the video only went as far as to account for 8 "4 billions" and it was already suggesting you'd only have a 1-in-4 billion chance of finding the right guess in several times the age of the universe using a multi-planetary giga-galactic super-computer.

The only way this operation would become compromised is if at some point a mathematical break-through happened that allowed a completely unknown approach to solving these computations, at which point the web's security and bitcoin would collapse before somebody would likely bother using it to brute-force your passwords.
