### ISSUE TITLE
Incorrect master password according to configuration

### ISSUE THREAD

**Issue by MistaTwista** [Lyndir/MasterPassword#213]
Hi, I'm using Master Password v2.6-cli-3-0-ga85eff42 in older versions if I enter wrong master password i will get wrong generated password silently. In this version if I enter wrong master password I get this message:
```
Incorrect master password according to configuration:
  /Users/<<USERNAME>>/.mpw.d/<<NAME_HERE>>.mpsites.json: Master password doesn't match key ID.
```

This is an issue as I think. If someone will run password generator for some known website or service he will know when generated password is right.
What do you think?
May be there is a way to configure old behaviour?

**Comment by lhunath** [comment]
The check is performed by means of the master key's keyID that's stored in the mpsites file. This check is very important to avoid the risk of you creating a password for a new site with a mistyped master password, resulting in a password you'll never be able to recover.

The security risk of this check is negligible due to the security properties of the Master Password algorithm, ie. the scrypt phase combined with the fact that the key ID is a sha256 of a 512-bit message.

**Comment by MistaTwista** [comment]
Most modern services have recover password function. It is not a problem to make new password, or generate password twice for really important services. But it's still a problem if your file was stolen or you have hidden process that try to brute-force your master password locally. Can i turn off that function anyway?

**Comment by lhunath** [comment]
You can disable this with `-Fnone`.  But note that your worry is not entirely based in fact.  If Master Password was brute-forceable, it really wouldn't matter if an attacker had an mpsites file or your key ID.  They could simply use a leaked password hash instead for the same effect.  Master Password was designed specifically to foil brute-force attacks.  The key ID does not contribute any real weakness, only a perceived one.
